### ISSUE TITLE
Not specified encoding when opening yaml files

### ISSUE THREAD

**Issue by passionsfrucht** [macisamuele/language-formatters-pre-commit-hooks#91]
On Windows, with AFAIK all current python versions, 
the [default installation does not assume `utf-8` file encoding](https://www.python.org/dev/peps/pep-0540/).

This leads to decoding errors with perfectly fine YAML files
(PYTHONUTF8=1 was manually set before on this system):

```bash
bsh ❯ PYTHONUTF8=0 pre-commit run -a
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check Toml...............................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for case conflicts.................................................Passed
Check for added large files..............................................Passed
fix UTF-8 byte order marker..............................................Passed
Mixed line ending........................................................Passed
Check docstring is first.................................................Passed
Check vcs permalinks.....................................................Passed
black....................................................................Passed
Pretty format YAML.......................................................Failed
- hook id: pretty-format-yaml
- exit code: 1

Traceback (most recent call last):
  File "d:\devel\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\devel\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\.cache\pre-commit\repo1kdjaww0\py_env-python3.9\Scripts\pretty-format-yaml.EXE\__main__.py", line 7, in <module>
  File "C:\Users\XXX\.cache\pre-commit\repo1kdjaww0\py_env-python3.9\lib\site-packages\language_formatters_pre_commit_hooks\pretty_format_yaml.py", line 71, in pretty_format_yaml
    string_content = "".join(input_file.readlines())
  File "d:\devel\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3321: character maps to <undefined>

pyupgrade................................................................Passed
Reorder python imports...................................................Passed
.gitlab-ci.yml linter....................................................Passed
markdownlint.............................................................Passed
autoflake................................................................Passed
nbstripout...............................................................Passed

XXXX@currywurst in …/nimbus-evaluation on  main [$] is 📦 v0.1.0 via 🐍 pyenv Mem: 18GiB/32GiB Sw: 12GiB/33GiB took 6s
bsh ❯ uname -a
MINGW64_NT-10.0-19043 currywurst 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys

```

with, shortened: 

```yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent
    - '2'
    - --preserve-quotes
```

Please note: https://github.com/yaml/pyyaml/issues/123

**Comment by macisamuele** [comment]
Fixed by #92
